version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - apt-get update
      - apt-get install -y yarn
  pre_build:
    on-failure: ABORT
    commands:
      - yarn
  build:
    on-failure: ABORT
    commands:
      - yarn run build
  post_build:
    commands:
      - aws s3 sync ./build s3://training-aws-willie
      - aws cloudfront create-invalidation --distribution-id EGTJ6A3MPYC15 --paths '/*'
